version: '3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=nest
      - POSTGRES_PASSWORD=nest
      - POSTGRES_DB=txxn
    ports:
      - 5432:5432
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - ${DOCKER_ADMINER_PORT:-3333}:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db
